org.gradle.jvmargs=-Xmx13312m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+UseStringDeduplication -XX:+OptimizeStringConcat -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.workers.max=4
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.daemon=true
kotlin.daemon.jvmargs=-Xmx4096m -XX:+UseG1GC
kotlin.compiler.execution.strategy=in-process
kotlin.incremental=true
kotlin.incremental.compilation=true
kotlin.caching.enabled=true
android.enableBuildCache=true
android.enableAapt2=true
android.enableR8.fullMode=false
android.defaults.buildfeatures.buildconfig=true
android.lint.useK2Uast=false
org.gradle.logging.level=lifecycle
org.gradle.console=auto
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
org.gradle.configuration-cache=true
